<?php
	if ( ! defined( 'ABSPATH' ) ) {
		exit; // Exit if accessed directly
	} ?>
    <div class="tab_item" data-tabs="#abptf_pdf">
        <h2 class="_abp_color_theme"> PDF Configuration</h2>
        <div class="_divider"></div>
        <i class="_color_7_fs_label_mar_tb_d_block">Manage all PDF-related settings from a single place. These options allow you to customize the appearance, branding, colors, and footer content of all PDF documents generated by TransportForge, including rental agreements, booking confirmations, invoices, passenger lists, and other downloadable documents.</i>
        <table class="_abp_fixed_text_left_mt">
            <tbody>
            <tr>
                <th class="_color_theme">PDF Background Image</th>
                <td colspan="3"> Upload a custom background image to enhance the visual appearance of your PDF documents and reinforce your brand identity.</td>
            </tr>
            <tr>
                <th class="_color_theme">PDF Logo</th>
                <td colspan="3"> Upload your company logo to display on all generated PDF documents. A branded logo helps create a professional and trustworthy experience for your customers.</td>
            </tr>
            <tr>
                <th class="_color_theme">PDF Logo Height</th>
                <td colspan="3"> Define the logo height in pixels to ensure it fits perfectly within the PDF layout without affecting document readability.</td>
            </tr>
            <tr>
                <th class="_color_theme">Background Color</th>
                <td colspan="3"> Choose a background color that complements your brand and improves the overall presentation of generated PDF files.</td>
            </tr>
            <tr>
                <th class="_color_theme">Text Color</th>
                <td colspan="3"> Select the primary text color used throughout PDF documents to maintain readability and visual consistency.</td>
            </tr>
            <tr>
                <th class="_color_theme">Terms & Conditions Title</th>
                <td colspan="3"> Specify a custom heading for the Terms & Conditions section that appears at the bottom of generated PDF documents.</td>
            </tr>
            <tr>
                <th class="_color_theme">Terms & Conditions Text</th>
                <td colspan="3"> Enter the terms, policies, disclaimers, or additional information you want customers to see in the footer section of all generated PDF documents.</td>
            </tr>
            </tbody>
        </table>
        <div class="_mar_tb" data-image-href="<?php echo esc_url( ABPRF_DOC_URL . '/' ) ?>image/pdf.png"><img class="_img_control" src="#" alt="PDF"></div>
    </div>
<?php
